fix gh action pipeline error
error details below:

ERROR:  Error installing rubygems-update:
  There are no versions of rubygems-update (= 3.5.4) compatible with your Ruby & RubyGems
  rubygems-update requires Ruby version >= 3.0.0. The current ruby version is 2.7.7.221.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
Updating rubygems-update
Error: Process completed with exit code 1.